config/routes.rb
Authentication::Application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config

  ActiveAdmin.routes(self)

  match "/login" => 'user_sessions#new', :as => :login
  match "/do_login" => 'user_sessions#create', :as => :do_login
  match "/logout" => 'user_sessions#destroy', :as => :logout
  match "/check_user" => 'user_sessions#check_user', :as => :check
  root :to => 'users#index'
  resources :users
  match "signin" => "oauth#start"
  match "callback" => "oauth#callback", as: :oauth_callback
  match "failure" => "oauth#failure"

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/code.rb
class Code < ActiveRecord::Base
  belongs_to :user
  attr_accessible :generated_code

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :login, :password, :password_confirmation, :two_step_auth, :code, :remember_token

  before_save :create_remember_token

  has_many :codes

  has_secure_password

  validates :login, presence: true, uniqueness: true
  validates_confirmation_of :password
  validates :password, presence: true, length: {minimum: 3}
  #validates :password_confirmation, presence: true
  validates :email, :presence => true,
            :uniqueness => true,
            :format => {:with => /^([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})$/i}

  self.per_page = 10

  def self.authenticate(login_or_email, pass)
    user = User.find_by_email(login_or_email) || User.find_by_login(login_or_email)
    if user && user.check_password(pass)
      user
    else
      nil
    end
  end

  def check_password(unencrypted_password)
    BCrypt::Password.new(self.password_digest) == unencrypted_password
  end

  def update_activation_code!
    code = self.codes.build(generated_code: generate_code(self.email))
    code.save
  end

  def generate_code(email)
    Digest::SHA512.hexdigest("#{email}:#{salt}").gsub(/[a-z]/i, "")[0..5]
  end

  def salt
    SecureRandom.hex(32)
  end

  def get_activation_code
    self.codes.last.generated_code
  end

  def self.find_by_activation_code code
    code = Code.find_by_generated_code(code)
    result = nil

    if code
      user = code.user
      created_at = code.created_at
      code.destroy

      result = user if user && (Time.now - created_at < 32)
    end

    result
  end

  def self.find_from_facebook(opts)
    user = User.find_by_email(opts["email"])
    if user

      return user
    else

      return User.create(login: opts["name"], email: opts["email"], password: BCrypt::Password.create(rand 999999), two_step_auth: true)
    end
  end

  private

  def create_remember_token
    self.remember_token = SecureRandom.urlsafe_base64
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include UserSessionsHelper
end

app/controllers/oauth_controller.rb
class OauthController < ApplicationController
  before_filter :oauth
  
  def start
    redirect_to @oauth.url_for_oauth_code(:permissions=>"email")
  end

  def callback
    if params[:error]
      redirect_to login_path, :notice => params[:error_description]
    else
      graph = Koala::Facebook::API.new(@oauth.get_access_token(params[:code]))
      email_and_name = graph.get_object("/me?fields=name,email")
      @user = sign_in_and_get_location User.find_from_facebook(email_and_name)
      redirect_to @user
    end
  end
  
  private

  def oauth
    @oauth ||= Koala::Facebook::OAuth.new(APP_ID, APP_SECRET,REDIRECT_URI)
  end

end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController

  def new
    #store_location
    #redirect_to current_user if signed_in?
    respond_to do |format|
        format.html
        format.js
    end
  end

  def check_user
    @user = User.authenticate(params[:login], params[:password])
    if @user
      if @user.two_step_auth
        @user.update_activation_code!
        respond_to do |format|
          format.html
          format.js
        end
      else
        @user = sign_in_and_get_location @user
        respond_to do |format|
          format.html {redirect_to @user}
          format.js {render "user_sessions/create"}
        end
      end
    else
      flash[:notice] = "Wrong Login, Email or Password"
      render :new
    end
  end

  def create
    @user = User.find_by_activation_code(params[:code])
    if @user
      @user = sign_in_and_get_location @user
      respond_to do |format|
        format.html {redirect_to @user}
        format.js
      end
    else
      flash[:notice] = "Wrong Code or Time Expired  "
      respond_to do |format|
        format.html {redirect_to login_path}
        format.js {render 'user_sessions/new'}
      end
    end
  end

  def destroy
    sign_out
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    before_filter :save_user_to_go, only: :show
    before_filter :signed?, except: [:new, :create, :index]

    # GET /users
    # GET /users.json
    def index
      @users = User.paginate(page: params[:page])
      respond_to do |format|
        format.html # index.html.erb
      end
    end

    # GET /users/1
    # GET /users/1.json
    def show
      @user = User.find(params[:id])
      respond_to do |format|
        format.html # show.html.erb
        format.json { render json: @user }
      end
    end

    # GET /users/new
    # GET /users/new.json
    def new
      @user = User.new

      respond_to do |format|
        format.html # new.html.erb
        format.json { render json: @user }
      end
    end

    # GET /users/1/edit
    def edit
      @user = User.find(params[:id])
    end

    # POST /users
    # POST /users.json
    def create
      @user = User.new(params[:user])

      respond_to do |format|
        if @user.save
          sign_in_user @user
          format.html { redirect_to @user, notice: 'User was successfully created.' }
          format.json { render json: @user, status: :created, location: @user }
        else
          format.html { render action: "new" }
          format.json { render json: @user.errors, status: :unprocessable_entity }
        end
      end
    end

    # PUT /users/1
    # PUT /users/1.json
    def update
      @user = User.find(params[:id])

      respond_to do |format|
        if @user.update_attributes(params[:user])
          sign_in_user @user
          format.html { redirect_to @user, notice: 'User was successfully updated.' }
          format.json { head :no_content }
        else
          format.html { render action: "edit" }
          format.json { render json: @user.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /users/1
    # DELETE /users/1.json
    def destroy
      @user = User.find(params[:id])
      @user.destroy

      respond_to do |format|
        format.html { redirect_to users_url }
        format.json { head :no_content }
      end
    end

  private

    def save_user_to_go
      if request.xhr?
        store_user_location params[:id]
      end

    end

    def signed?
      redirect_to :login unless signed_in?
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/user_helper.rb
module UserHelper

  def link_to_gravatar(email, size=150)
    "http://www.gravatar.com/avatar/#{Digest::MD5.hexdigest(email)}?d=wavatar&s=#{size}"
  end

  def link_to_user(user)
    if signed_in?
      link_to "Show", user_path(user), class: 'btn'
    else
      link_to "Show", user_path(user), class: 'btn', remote: true
    end
  end

end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
  def sign_in_user(user)
    cookies.permanent[:remember_token] = user.remember_token
    self.current_user = user
  end

  def signed_in?
    !current_user.nil?
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    @current_user ||= User.find_by_remember_token(cookies[:remember_token])
  end

  def sign_out
    delete_user_location
    self.current_user = nil
    cookies.delete(:remember_token)
  end

  def get_user_location
    begin

      user = User.find(session[:return_to_user])
    rescue

      nil
    end
  end

  def delete_user_location
    session[:return_to_user] = nil
  end

  def store_user_location(user_id)
    session[:return_to_user] = user_id
  end

  def sign_in_and_get_location(user)
    sign_in_user user
    user = get_user_location || user
    delete_user_location

    user
  end

end

app/views/layouts/_header.html.slim
.navbar.navbar-fixed-top
  .navbar-inner
    .container
      a.btn.btn-navbar data-target=".nav-collapse" data-toggle="collapse"
        span.icon-bar
        span.icon-bar
        span.icon-bar
      a.brand href="/" Authentication
      .container.nav-collapse
        ul.nav.pull-right
          li= link_to "Admin Panel", admin_root_path
          li= link_to "Users", users_path
          - if signed_in?
            li= link_to current_user.login, current_user, id: "current_user"
            li= link_to "LogOut", logout_path, id: "logout"
          - else
            li= link_to "SignUp", new_user_path, id: "sign_in"
            li= link_to "LogIn", login_path, id: "login", remote: true
            li= link_to "LogIn via Facebook", :controller => 'oauth', :action => 'start'

app/views/layouts/application.html.slim
doctype html
html lang="en"
  head
    meta charset="utf-8"
    title= content_for?(:title) ? yield(:title) : "Authentication"
    = csrf_meta_tags
    /! Le HTML5 shim, for IE6-8 support of HTML elements
    /![if lt IE 9]
      | <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    = stylesheet_link_tag "application", :media => "all"
  body
    = render "layouts/header"
    .container
      .content
        .row
          .offset3.span6
            = yield
      footer
        p © Altoros 2012
    = debug params
    = debug session
    = javascript_include_tag "application"
    .modal.hide.fade#login-modal
      .modal-header
        button.close type="button" data-dismiss="modal" aria-hidden="true" &times;
        h3 Login
      .modal-body
        p#login-body

app/views/user_sessions/_code_form.html.erb
<div class="show">
  <p id="code" class="alert"><%= @user.get_activation_code %></p>
  <%= form_tag( url_for(controller: "user_sessions", action: "create"), :class => 'form-horizontal', remote: true) do %>
      <div class="control-group">
        <%= label_tag :code, "Code", :class => 'control-label' %>
        <div class="controls">
          <%= text_field_tag :code, nil, :placeholder => 'Enter Code here in 30 sec...', :class => 'text_field' %>
        </div>
      </div>
      <div class="form-actions">
        <%= submit_tag "Submit", :class => 'btn btn-primary' %>
      </div>
  <% end %>
</div>

app/views/user_sessions/_login_form.html.erb
<%= form_tag( url_for(controller: "user_sessions", action: "check_user"), class: 'form-horizontal', remote: true) do %>
    <div class="control-group">
      <%= label_tag :login, "Login or Email", :class => 'control-label' %>
      <div class="controls">
        <%= text_field_tag :login, nil, :placeholder => 'Enter Login or Email here...', :class => 'text_field' %>
      </div>
    </div>
    <div class= "control-group" >
      <%= label_tag :password, "Password", :class => 'control-label' %>
      <div class="controls">
        <%= password_field_tag :password, nil, :placeholder => 'Enter Password here...', :class => 'text_field' %>
      </div>
    </div>
    <div class="form-actions">
      <%= submit_tag "LogIn", :class => 'btn btn-primary' %>
      <%= link_to "LogIn via Facebook", url_for(:controller => 'oauth', :action => 'start'), :class => 'btn btn-primary' %>
    </div>
<% end %>

app/views/user_sessions/check_user.html.slim
.show
  p#code.alert= @user.get_activation_code
  = form_tag( url_for(controller: "user_sessions", action: "create"), :class => 'form-horizontal') do
    .control-group
      = label_tag :code, "Code", :class => 'control-label'
      .controls
        = text_field_tag :code, nil, :placeholder => 'Enter Code here in 30 sec...', :class => 'text_field'
    .form-actions
      = submit_tag "Submit", :class => 'btn btn-primary'

app/views/user_sessions/check_user.js.erb
$("p#login-body").html("").append("<%= escape_javascript(render "code_form") %>");

app/views/user_sessions/create.js.erb
$("p#login-body").html("")
$("div.modal").modal('toggle');
$("div.navbar.navbar-fixed-top").replaceWith("<%= j render "layouts/header" %>")
$(".offset3.span6").html("").append("<%= j render(template: "users/show") %>")

app/views/user_sessions/new.html.slim
- if notice
  p.alert.alert-warning= notice
= form_tag( url_for(controller: "user_sessions", action: "check_user"), class: 'form-horizontal') do
  .control-group
    = label_tag :login, "Login or Email", :class => 'control-label'
    .controls
      = text_field_tag :login, nil, :placeholder => 'Enter Login or Email here...', :class => 'text_field'
  .control-group
    = label_tag :password, "Password", :class => 'control-label'
    .controls
      = password_field_tag :password, nil, :placeholder => 'Enter Password here...', :class => 'text_field'
  .form-actions
    = submit_tag "Submit", :class => 'btn btn-primary'

app/views/user_sessions/new.js.erb
$("p#login-body").html("").append("<%= escape_javascript(render "login_form") %>");
$("div.modal").modal('show');

app/views/users/_form.html.slim
= form_for @user, :html => { :class => 'form-horizontal' } do |f|
  .control-group
    = f.label :login, :class => 'control-label'
    .controls
      = f.text_field :login, :class => 'text_field'
  .control-group
    = f.label :password, :class => 'control-label'
    .controls
      = f.password_field :password, :class => 'text_field'
  .control-group
    = f.label :password_confirmation, :class => 'control-label'
    .controls
      = f.password_field :password_confirmation, :class => 'text_field'
  .control-group
    = f.label :email, :class => 'control-label'
    .controls
      = f.text_field :email, :class => 'text_field'
  .control-group
    = f.label :two_step_auth, :class => 'control-label'
    .controls
      = f.check_box :two_step_auth, :class => 'check_box'
  .form-actions
    = f.submit nil, :class => 'btn btn-primary'
    = link_to t('.cancel', :default => t("helpers.links.cancel")), \
      users_path, :class => 'btn'

app/views/users/edit.html.slim
- model_class = User
.page-header
  h1= t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human, :default => "Edit #{model_class.model_name.human}")
= render :partial => 'form'

app/views/users/index.html.slim
- model_class = User
.page-header
  h1= t '.title', :default => model_class.model_name.human.pluralize
/.alert= @email.to_s
.apple_pagination
  = will_paginate @users, :container => false
table.table.table-striped
  thead
    tr
      th= model_class.human_attribute_name(:login)
      th= model_class.human_attribute_name(:email)
      th= model_class.human_attribute_name(:gravatar)
      th
  tbody
    - @users.each do |user|
      tr
        td= user.login
        td= user.email
        td= image_tag link_to_gravatar user.email, 50
        td= link_to_user user

= link_to t('.new', :default => t("helpers.links.new")), new_user_path, :class => 'btn btn-primary'

app/views/users/new.html.slim
- model_class = User
.page-header
  h1= t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human, :default => "New #{model_class.model_name.human}")
= render :partial => 'form'

app/views/users/show.html.slim
- model_class = User
.page-header
  h1= t '.title', :default => model_class.model_name.human
dl.dl-horizontal
  dt
    strong
      = model_class.human_attribute_name(:gravatar)
  dd= image_tag link_to_gravatar @user.email, 150
  dt
    strong
      = model_class.human_attribute_name(:login)
  dd= @user.login
  - if @user.id == current_user.id
    dt
      strong
        = model_class.human_attribute_name(:email)
    dd= @user.email
  dt
    strong
      = model_class.human_attribute_name(:two_step_auth)
  dd= @user.two_step_auth
.form-actions
  = link_to t('.back', :default => t("helpers.links.back")), users_path, :class => 'btn'
  = link_to t('.edit', :default => t("helpers.links.edit")), edit_user_path(@user), :class => 'btn'
  = link_to t('.destroy', :default => t("helpers.links.destroy")), user_path(@user), :method => 'delete',       \
    :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },\
    :class => 'btn btn-danger'